// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package ttnpb

var EndDeviceBrandFieldPathsNested = []string{
	"brand_id",
	"brand_name",
	"end_devices",
}

var EndDeviceBrandFieldPathsTopLevel = []string{
	"brand_id",
	"brand_name",
	"end_devices",
}
var EndDeviceDefinitionFieldPathsNested = []string{
	"definition_id",
	"description",
	"firmware_versions",
	"hardware_versions",
	"key_provisioning",
	"key_security",
	"name",
	"photos",
	"photos.main",
	"photos.other",
	"sensors",
}

var EndDeviceDefinitionFieldPathsTopLevel = []string{
	"definition_id",
	"description",
	"firmware_versions",
	"hardware_versions",
	"key_provisioning",
	"key_security",
	"name",
	"photos",
	"sensors",
}
var ListEndDeviceBrandsRequestFieldPathsNested = []string{
	"brand_id",
	"limit",
	"offset",
	"order_by",
}

var ListEndDeviceBrandsRequestFieldPathsTopLevel = []string{
	"brand_id",
	"limit",
	"offset",
	"order_by",
}
var ListEndDeviceDefinitionsRequestFieldPathsNested = []string{
	"brand_id",
	"field_mask",
	"limit",
	"model_id",
	"offset",
	"order_by",
	"search",
}

var ListEndDeviceDefinitionsRequestFieldPathsTopLevel = []string{
	"brand_id",
	"field_mask",
	"limit",
	"model_id",
	"offset",
	"order_by",
	"search",
}
var ListEndDeviceBrandsResponseFieldPathsNested = []string{
	"brands",
}

var ListEndDeviceBrandsResponseFieldPathsTopLevel = []string{
	"brands",
}
var ListEndDeviceDefinitionsResponseFieldPathsNested = []string{
	"definitions",
}

var ListEndDeviceDefinitionsResponseFieldPathsTopLevel = []string{
	"definitions",
}
var EndDeviceDefinition_VersionFieldPathsNested = []string{
	"version",
}

var EndDeviceDefinition_VersionFieldPathsTopLevel = []string{
	"version",
}
var EndDeviceDefinition_FirmwareVersionFieldPathsNested = []string{
	"hardware_versions",
	"profiles",
	"version",
}

var EndDeviceDefinition_FirmwareVersionFieldPathsTopLevel = []string{
	"hardware_versions",
	"profiles",
	"version",
}
var EndDeviceDefinition_PhotosFieldPathsNested = []string{
	"main",
	"other",
}

var EndDeviceDefinition_PhotosFieldPathsTopLevel = []string{
	"main",
	"other",
}
var EndDeviceDefinition_FirmwareVersion_ProfileFieldPathsNested = []string{
	"codec_id",
	"lorawan_certified",
	"profile_id",
}

var EndDeviceDefinition_FirmwareVersion_ProfileFieldPathsTopLevel = []string{
	"codec_id",
	"lorawan_certified",
	"profile_id",
}
